const phraseList = [
  'better late than never',
  'every cloud has a silver lining',
  'ignorance is bliss',
  'many hands make light work',
  'honesty is the best policy',
  'always put your best foot forward',
  'out of sight out of mind',
  'practice makes perfect',
  'easy come easy go',
  'look before you leap',
  'learn to walk before you run',
  'no news is good news',
  'it takes two to tango',
  'the cat is out of the bag',
  'the early bird catches the worm',
  'fortune favours the bold',
  'curiosity killed the cat',
  'the pen is mightier than the sword',
  'a picture is worth a thousand words',
  'a rising tide lifts all boats',
  'there is no place like home',
  'actions speak louder than words',
  'good things come to those who wait',
  'too many cooks spoil the broth',
  'strike while the iron is hot',
  'a friend in need is a friend indeed'
];